Add CLI command #3
easydigitaldownloads/edd-discount-code-generator pull request #10
Opened 2021-05-10 15:20 UTC by ashleyfae

Closes #3

2021-05-19 17:02 UTC, LisaCee commented on includes/discount-actions.php
> +		return new WP_Error( 'invalid_number_codes', __( 'The supplied number of codes is invalid. Please enter an integer creater than zero.', 'edd_dcg' ) );
Typo here - "greater"

2021-05-19 18:07 UTC, LisaCee commented
I'm having some difficulties declaring the amount type through the CLI.  It defaults to percent, as expected, but percent doesn't show in `_edd_discount_type` - it's just blank - but the discounts behaves as expected.  I haven't been able to create a flat discount yet, though.  This is the command I'm using `lando wp edd generate:discounts cliflat5 --amount=5 --amount-type="flat"
`.  I've tried reordering the arguments and once I forgot the quotes around the type, but I can't get any to register as a flat amount discount.

2021-05-19 19:06 UTC, robincornett requested changes

2021-05-19 19:06 UTC, robincornett commented on includes/class-cli.php
> +			WP_CLI::success( esc_html__( 'Discounts successfully created.', 'edd_dcg' ) );
```suggestion
			WP_CLI::success( esc_html__( 'Discount codes successfully created.', 'edd_dcg' ) );
```
I was thinking to make it more consistent with the UI (would be nice if they said the same thing), but that one just says "45 codes generated." ... I like that this says successfully, so maybe we could update the UI to say that as well. Made a comment that it would be nice if we could send the number of codes generated back to this message so that we could really achieve parity.

2021-05-21 10:25 UTC, ashleyfae commented
Updated to hopefully fix `amount-type` issue and to show number of discounts created in success message.

2021-05-21 14:32 UTC, robincornett commented on includes/class-cli.php
> +	 * [--once]
Question: how am I supposed to use this particular flag? Since there is no `=` in the docs my inclination was that using it at all would enable it, meaning that:

```
wp edd generate:discounts edd30-beta2 --number=5 --amount=15 --amount-type=percent --max-uses=1 --expiration=6/30/2021 --once
```
would generate codes which could only be used once per customer. It didn't work, though, and logging the `$code` array that's used to actually send the data to EDD had `once_per_customer` as an empty arg.

I also tried `--once=true`, which also did not work. `--once==1` did work, but I feel like that's not how it's supposed to be?

2021-05-21 15:08 UTC, ashleyfae commented on includes/class-cli.php
> +	 * [--once]
It's supposed to be `--once` . When used, that makes it one-time use. When not used, it's not one time. If that's not working, I'll take a look.

2021-05-21 15:29 UTC, ashleyfae commented on includes/class-cli.php
> +	 * [--once]
Think I fixed it. https://github.com/easydigitaldownloads/edd-discount-code-generator/pull/10/commits/09a61768dccb1070d7769f40ecbc541a9f23eb4f

2021-05-24 12:15 UTC, robincornett reviewed
Overall, this is working well--just a couple of questions.

2021-05-24 12:15 UTC, robincornett commented on includes/discount-actions.php
> +		return new WP_Error( 'missing_number_codes', __( 'Please specify a number of codes to generate.', 'edd_dcg' ) );
I'm trying to deliberately trigger one of these errors and just get the default EDD message:

>There was a problem adding that discount code, please try again.

Is the result of the `WP_Error` supposed to be used anywhere?

2021-05-24 13:21 UTC, ashleyfae commented on includes/discount-actions.php
> +		return new WP_Error( 'missing_number_codes', __( 'Please specify a number of codes to generate.', 'edd_dcg' ) );
That particular case probably will never get used. [The CLI does use WP_Error](https://github.com/easydigitaldownloads/edd-discount-code-generator/blob/09a61768dccb1070d7769f40ecbc541a9f23eb4f/includes/class-cli.php#L127-L128) but that particular one will probably never trigger since the CLI has a default.

That being said, it still makes sense to return `WP_Error` over an empty `return` to be consistent with all other errors.

2021-05-24 13:22 UTC, ashleyfae commented on includes/class-cli.php
> +	 * : If not set and products are specified, discounts will only apply to selected products. If set, discounts will
Can you think of a good opposite word that isn't "not global" :P

2021-05-24 13:51 UTC, robincornett commented on includes/class-cli.php
> +	 * default: any
I think the default for the UI is `all`.

2021-05-24 13:56 UTC, robincornett commented on includes/class-cli.php
> +	 * : If not set and products are specified, discounts will only apply to selected products. If set, discounts will
Well, no, which is why I didn't suggest one originally 🤣  ... `--selected` might be one? It's not as efficient, but you could change it to `--scope=global` as the default and then to set it to specific downloads it would be `--scope=not_global`. `scope` is the `name` attribute for the input in 3.0.

2021-05-24 14:01 UTC, ashleyfae commented on includes/class-cli.php
> +	 * : If not set and products are specified, discounts will only apply to selected products. If set, discounts will
Scope works for me.

2021-05-24 14:40 UTC, robincornett commented on includes/class-cli.php
> +			$final_args['not_global'] = ! empty( $final_args['scope'] ) && 'not_global' === $final_args['scope'];
```suggestion
			$final_args['not_global'] = ! empty( $final_args['scope'] ) && 'not_global' === $final_args['scope'] ? 1 : 0;
```
(Because `edd_dcg_create_discount_codes` doesn't account for a boolean being passed, just string/int.)

2021-05-24 14:51 UTC, ashleyfae commented on includes/class-cli.php
> +			$final_args['not_global'] = ! empty( $final_args['scope'] ) && 'not_global' === $final_args['scope'];
I think it does account for that. https://github.com/easydigitaldownloads/edd-discount-code-generator/blob/issue/3/includes/discount-actions.php#L96 It does an `! empty()` check.

2021-05-24 14:57 UTC, robincornett commented on includes/class-cli.php
> +			$final_args['not_global'] = ! empty( $final_args['scope'] ) && 'not_global' === $final_args['scope'];
That works for EDD 3.0, because it's checking back to the original `$data`, but if I set `--scope=not_global` in 2.10, then the boolean misses the check here: https://github.com/easydigitaldownloads/edd-discount-code-generator/blob/issue/3/includes/discount-actions.php#L63 and the code is set to global.

2021-05-24 15:02 UTC, ashleyfae commented on includes/class-cli.php
> +			$final_args['not_global'] = ! empty( $final_args['scope'] ) && 'not_global' === $final_args['scope'];
Ah, good catch.

2021-05-24 15:07 UTC, robincornett approved these changes

2021-05-24 15:57 UTC, merged