Issue/11
easydigitaldownloads/edd-discount-code-generator pull request #12
Opened 2021-05-26 17:58 UTC by LisaCee

Fixes #11 

Proposed changes:
- If in 3.0, format end time of discount to include default end time (23:59)

There are a lot of different ways to format the date. I chose to model this after [this function](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/f7e238c466a629f723d8efd2fa311fbb41db71fc/includes/discount-functions.php#L403-L406) in discount-functions, but I am open to suggestions.

2021-05-27 07:49 UTC, ashleyfae requested changes

2021-05-27 07:49 UTC, ashleyfae commented on includes/discount-actions.php
> +			$code['expiration'] = date( 'Y-m-d', strtotime( $code['expiration'] ) . '23:59:59' );
Very close, but let's put `23:59:59` directly inside the date format like this:

```suggestion
			$code['expiration'] = date( 'Y-m-d 23:59:59', strtotime( $code['expiration'] ) );
```

The first parameter of `date()` normally accepts a format string, but you can also pass in literal numbers as well.

2021-06-01 11:39 UTC, ashleyfae approved these changes

2021-06-01 12:11 UTC, robincornett approved these changes

2021-06-01 12:13 UTC, merged